#!/usr/bin/env node
/**
 * Build orchestrator.
 *
 * Assembles a loadable extension directory per target browser by combining the
 * shared sources in `src/` with the platform manifest in `platform/<target>/`.
 *
 *   node build-scripts/build.js firefox chrome safari
 *
 * The Firefox manifest is the single source of truth for the background script
 * list: Manifest V3 service workers cannot declare multiple scripts, so the
 * same list is emitted as an `importScripts()` loader for those targets.
 */

const fs = require('fs');
const path = require('path');

const ROOT = path.resolve(__dirname, '..');
const SRC_DIR = path.join(ROOT, 'src');
const PLATFORM_DIR = path.join(ROOT, 'platform');
const BUILD_DIR = path.join(ROOT, 'build');

const TARGETS = ['firefox', 'chrome', 'safari'];

// Firefox ships SVG icons; Chromium and Safari only accept raster icons.
const ICON_EXTENSION = { firefox: '.svg', chrome: '.png', safari: '.png' };

const SERVICE_WORKER_PATH = 'js/background-service-worker.js';

function readJSON(file) {
  return JSON.parse(fs.readFileSync(file, 'utf8'));
}

function rimraf(target) {
  fs.rmSync(target, { recursive: true, force: true });
}

function copyTree(from, to, filter) {
  fs.mkdirSync(to, { recursive: true });
  for (const entry of fs.readdirSync(from, { withFileTypes: true })) {
    const src = path.join(from, entry.name);
    const dest = path.join(to, entry.name);
    if (entry.isDirectory()) {
      copyTree(src, dest, filter);
    } else if (filter(src)) {
      fs.copyFileSync(src, dest);
    }
  }
}

function backgroundScripts() {
  const firefoxManifest = readJSON(path.join(PLATFORM_DIR, 'firefox', 'manifest.json'));
  return firefoxManifest.background.scripts;
}

function serviceWorkerImports() {
  // importScripts() resolves relative to the worker's own URL, so paths are
  // rooted at the extension origin to stay independent of the worker location.
  return backgroundScripts().map((file) => `/${file}`);
}

function writeServiceWorker(outDir) {
  const scripts = serviceWorkerImports().map((file) => `'${file}'`).join(',\n  ');
  const contents = [
    '// Generated by build-scripts/build.js - do not edit.',
    '// Manifest V3 service workers accept a single entry point, so the shared',
    '// background scripts are imported here in manifest order.',
    'importScripts(',
    `  ${scripts}`,
    ');',
    ''
  ].join('\n');
  const dest = path.join(outDir, SERVICE_WORKER_PATH);
  fs.mkdirSync(path.dirname(dest), { recursive: true });
  fs.writeFileSync(dest, contents);
}

/**
 * Collect every extension-relative path a manifest points at, so a missing or
 * renamed file fails the build instead of the browser.
 */
function manifestReferences(manifest) {
  const refs = [];
  const background = manifest.background || {};
  refs.push(...(background.scripts || []));
  if (background.service_worker) refs.push(background.service_worker);
  for (const script of manifest.content_scripts || []) {
    refs.push(...(script.js || []), ...(script.css || []));
  }
  for (const resource of manifest.web_accessible_resources || []) {
    if (typeof resource === 'string') refs.push(resource);
    else refs.push(...(resource.resources || []));
  }
  const popup = (manifest.action || manifest.browser_action || {}).default_popup;
  if (popup) refs.push(popup);
  if (manifest.options_ui?.page) refs.push(manifest.options_ui.page);
  refs.push(...Object.values(manifest.icons || {}));
  return refs;
}

function verify(outDir, manifest) {
  const references = manifestReferences(manifest);
  if (manifest.background?.service_worker) {
    references.push(...serviceWorkerImports().map((file) => file.replace(/^\//, '')));
  }
  const missing = references
    .filter((ref) => !fs.existsSync(path.join(outDir, ref)));
  if (missing.length > 0) {
    throw new Error(`Manifest references missing files:\n  ${missing.join('\n  ')}`);
  }
}

function build(target, version) {
  const outDir = path.join(BUILD_DIR, target);
  const manifestPath = path.join(PLATFORM_DIR, target, 'manifest.json');

  if (!fs.existsSync(manifestPath)) {
    throw new Error(`No manifest for target "${target}" at ${manifestPath}`);
  }

  rimraf(outDir);

  const iconExtension = ICON_EXTENSION[target];
  copyTree(SRC_DIR, outDir, (file) => {
    const inIcons = path.dirname(file) === path.join(SRC_DIR, 'icons');
    return !inIcons || path.extname(file) === iconExtension;
  });

  const manifest = readJSON(manifestPath);
  manifest.version = version;

  if (manifest.background?.service_worker) {
    writeServiceWorker(outDir);
  }

  fs.writeFileSync(
    path.join(outDir, 'manifest.json'),
    `${JSON.stringify(manifest, null, 2)}\n`
  );

  // Safari's converter reads Info.plist overrides from the platform directory.
  const extras = fs.readdirSync(path.join(PLATFORM_DIR, target))
    .filter((file) => file !== 'manifest.json');
  for (const file of extras) {
    fs.copyFileSync(path.join(PLATFORM_DIR, target, file), path.join(outDir, file));
  }

  verify(outDir, manifest);
  console.log(`Built ${target} (v${version}) -> ${path.relative(ROOT, outDir)}`);
}

function main() {
  const args = process.argv.slice(2);
  const targets = args.length === 0 || args.includes('all') ? TARGETS : args;

  const unknown = targets.filter((target) => !TARGETS.includes(target));
  if (unknown.length > 0) {
    console.error(`Unknown target(s): ${unknown.join(', ')}`);
    console.error(`Available targets: ${TARGETS.join(', ')}`);
    process.exit(1);
  }

  const { version } = readJSON(path.join(ROOT, 'package.json'));
  for (const target of targets) {
    build(target, version);
  }
}

main();
